### ISSUE TITLE
Running the flask app causes issues if mongoDB is not set up

### ISSUE THREAD

**Issue by pchan37** [StuyCSDojo/dojo-website#12]
I will write a temporary patch to disable the database interaction and/or enable the database interaction.  I will need to update the documentation for installing and setting up mongo after doing some research.

**Comment by pchan37** [comment]
Updated documentation with instructions to install MongoDB on all three covered system.  Issue will be closed after instructions have been confirmed to be correct.

**Comment by TakingTheL** [comment]
For Windows x86, download `win32/mongodb-win32-i386-v3.0-latest.zip` from `https://www.mongodb.org/dl/win32/i386` instead. The rest of the instructions still holds.

**Comment by pchan37** [comment]
The documentation has been updated with instructions for installing MongoDB.  These instructions have since been verified and corrected.
