### ISSUE TITLE
Turn IRC into some kind of websocket chat client.

### ISSUE THREAD

**Issue by noobbyte** [StuyCSDojo/dojo-website#4]
Look into SocketIO and websockets for this.

**Comment by pchan37** [comment]
Norman has already updated the IRC channel and believes that we should continue using the IRC channel.

**Comment by noobbyte** [comment]
What do you mean by updated? The problem with IRC -- and chat in general, I suppose -- is that it needs an active monitor. Perhaps this issue should be merged into the proposal for a QA forum rather than a chat client.

**Comment by pchan37** [comment]
Norman is currently serving as the monitor and has wrote the following guide for the IRC channel.

[IRCGuide.pdf](https://github.com/StuyCSDojo/dojo-website/files/700536/IRCGuide.pdf)

**Comment by noobbyte** [comment]
I see -- we should have someone monitor the IRC channel, then. Closing the issue.
