### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by pchan37** [StuyCSDojo/dojo-website#9]

**Comment by pchan37** [comment]
A bug report just came in stating that the announcement page is not responsive (either you need to zoom out) to see all the letters.  After making the navbar responsive, try to make the announcement page responsive.  I can understand checking the announcement page on mobile, but forget the other pages unless there is spare time.

**Comment by TakingTheL** [comment]
Navbar now responsive with smaller screens.
Tested on Android 5.0, Chrome, on Note 3
iOS 10.2.1, Safari, Chrome, on iPhone 5s
Windows 10 Chrome, Edge, on small window
